name: go_router_riverpod
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # add
  # [기능]
  # App추가 / 연동기능 / 라이센스명 / 해당라이브러리 링크URL(1.github/2.pub.dev/3.홈페이지/4.없음, 우선 순위로 1개만)

  # [route]
  # Pub추가 / router / BSD-3-Clause / https://pub.dev/packages/go_router
  go_router: ^15.1.2

  # [status]
  # App추가 / 상태관리기능 / MIT / https://github.com/rrousselGit/riverpod
  flutter_riverpod: ^2.6.1
  # App추가 / 상태관리기능 / MIT / https://github.com/rrousselGit/riverpod
  riverpod_annotation: ^2.6.1

  # [Network]
  # App추가 / 통신모듈 / MIT / https://github.com/cfug/dio/tree/main/dio
  dio: ^5.8.0+1
  # App추가 / 통신모듈 / BSD-3-Clause / https://pub.dev/packages/http
  http: ^1.4.0
  # App추가 / 통신모듈 / MIT / https://github.com/trevorwang/retrofit.dart
  retrofit : ^4.4.2
  # App추가 / dio 로그 / MIT / https://pub.dev/packages/pretty_dio_logger
  pretty_dio_logger: ^1.3.1
  # App추가 / api object / MIT / https://pub.dev/packages/objectid
#  objectid: ^3.0.0

  # [image]
  # App추가 / 이미지 캐시 / MIT / https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.4.1
  # App추가 / svg / MIT / https://github.com/dnfield/flutter_svg/tree/master/packages/flutter_svg
  #  flutter_svg: ^2.0.10+1

  # [view]
  # App추가 / 웹뷰 / BSD-3-Clause / https://pub.dev/packages/webview_flutter
  #  webview_flutter: ^4.11.0
  # App추가 / 커스텀 그리드뷰 / MIT / https://pub.dev/packages/flutter_staggered_grid_view/
  #  flutter_staggered_grid_view: ^0.7.0
  # App추가 / 리프레쉬 리스트뷰 / MIT / https://pub.dev/packages/easy_refresh
  #  easy_refresh: ^3.3.4

  # [firebase]
  #  firebase_core: ^3.13.0
  #  firebase_auth: ^5.5.3
  #  firebase_in_app_messaging: ^0.8.1+5
  #  firebase_messaging: ^15.2.5

  # [utils]
  # App추가 / 프리퍼런스 / BSD-3-Clause / https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.5.3
  # App추가 / 로그 / MIT / https://pub.dev/packages/logger
  logger: ^2.5.0
  # App추가 / 토스트 1 / MIT / https://pub.dev/packages/fluttertoast
  #  fluttertoast: ^8.2.2
  # App추가 / 토스트 2 / BSD-3-Clause / https://pub.dev/packages/toastification
#  toastification: ^3.0.2
  # App추가 / 모델 Helper / BSD-3-Clause / https://github.com/google/json_serializable.dart/tree/master/json_annotation
  json_annotation: ^4.9.0
  # App추가 / 표준화 국제화 날짜 숫자등 / BSD-3-Clause / https://pub.dev/packages/intl
#  intl: ^0.18.1
  # App추가 / 로컬 노티피케이션 / BSD-3-Clause / https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications
  #  flutter_local_notifications: ^17.2.3
  # 오브젝트 비교
  #  equatable: ^2.0.5
  # 내부 보안 저장소
  #  flutter_secure_storage : ^9.0.0

  # [암호화 AES 양방향 SHA 단방향]
  #  crypto: ^3.0.3
  #  encrypt: ^5.0.3
  #  jwt_decoder: ^2.0.1

  # 권한체크
  #  permission_handler: ^10.4.3
  # App추가 / 디바이스 정보 조회 / BSD-3-Clause / https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus/device_info_plus
  #  device_info_plus: ^10.1.0
  # App추가 / 패키지 정보 조회 / BSD-3-Clause / https://github.com/fluttercommunity/plus_plugins/tree/main/packages/package_info_plus/package_info_plus
  #  package_info_plus: ^8.0.1
  # App추가 / 디바이스 아이디 조회 / MIT / https://github.com/GigaDroid/flutter_udid
#  flutter_udid: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  go_router_builder: ^2.9.0 # dart run build_runner build
  riverpod_generator: ^2.6.5
  retrofit_generator: ^9.2.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NanumSquareRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundEB.ttf
          weight: 800
        - asset: assets/fonts/NanumSquareRoundB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareRoundR.ttf
          weight: 400
        - asset: assets/fonts/NanumSquareRoundL.ttf
          weight: 300

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
